### ISSUE TITLE
None of the examples compile/build with latest Espressif Toolchain change to CMake

### ISSUE THREAD

**Issue by jcabad100** [PacktPublishing/Internet-of-Things-Projects-with-ESP32#1]
I got the latest version of the Espressif toolchain for EPS32 and none of the examples in the book can be compiled/build because the new tool chain use CMake instead of Make....would it be possible to suggest how to migrate at least for one or two examples? Thank you very much!

**Comment by jcabad100** [comment]
Following the new tool chain "blink" example (which uses CMake) i manage to build the book Chapter 1 "blinking" example by doing the following: 

A) Add the following file: ...\esp\esp-idf\examples\IoTBook\Chapter01\blinking\main\CMakeLists.txt
whose content is:

set(COMPONENT_SRCS "blinking.c")
set(COMPONENT_ADD_INCLUDEDIRS ".")
register_component()

B) Add the following file:  ...esp\esp-idf\examples\IoTBook\Chapter01\blinking\ CMakeLists.txt

"# The following five lines of boilerplate have to be in your project's"
"# CMakeLists in this exact order for cmake to work correctly"
cmake_minimum_required(VERSION 3.5)

include($ENV{IDF_PATH}/tools/cmake/project.cmake)
project(blinking)

NOTE1: Do not use the " " marks to enclose the comment, i did it because this website understand it as HTML and render the text in large fonts. 
NOTE2: The first file goes into the "main" folder and the second one on the project root folder.

C) After that i manage to build and flash the blinking example with following two separated commands on the GitBash (first navigating to the project root directory ...esp\esp-idf\examples\IoTBook\Chapter01\blinking\  ): 
idf.py build
idf.py -p COM8 flash
NOTE: Make sure the CoolTerm has not an open connection on the same COM port of course, otherwise it is not possible to flash of course.

**Comment by gaurav-packt** [comment]
Hello,

For successful execution of the examples, we would recommend you to kindly use  Espressif toolchain for EPS32 version mentioned in the book.
