### ISSUE TITLE
Chapter 02 - DHT example cannot be built "dht.h: No such file or directory"

### ISSUE THREAD

**Issue by jcabad100** [PacktPublishing/Internet-of-Things-Projects-with-ESP32#2]
I tried to build the Chapter 02 examples as i successfully managed with Chapter 01 "blinking" application (using CMake for the new toolchain version) and starting with the DHT sensor example....

A) Add the following file: ...esp-idf\examples\IoTBook\Chapter02\dhtdemo\main\CMakeLists.txt

set(COMPONENT_SRCS "dhtdemo.c")
set(COMPONENT_ADD_INCLUDEDIRS ".")

register_component()

B) Add the following file: ...esp-idf\examples\IoTBook\Chapter02\dhtdemo\CMakeLists.txt

"# The following five lines of boilerplate have to be in your project's"
"# CMakeLists in this exact order for cmake to work correctly"
cmake_minimum_required(VERSION 3.5)

include($ENV{IDF_PATH}/tools/cmake/project.cmake)
project(dhtdemo)

NOTE1: Do not use the " " marks to enclose the comment, i did it because this website understand it as HTML and render the text in large fonts.
NOTE2: The first file goes into the "main" folder and the second one on the project root folder.

C) After that i treied to build the DHT example with following t commands on the GitBash (first navigating to the project root directory ....esp-idf\examples\IoTBook\Chapter02\dhtdemo\ ):
idf.py build ...but then i get the following error:

DELL@DESKTOP-MVQO1NB MINGW64 ~/esp/esp-idf/examples/IoTBook/Chapter02/dhtdemo (master)
$ idf.py build
Checking Python dependencies...
Python requirements from C:\Users\DELL\esp\esp-idf\requirements.txt are satisfied.
Running ninja in directory c:\users\dell\esp\esp-idf\examples\iotbook\chapter02\dhtdemo\build
Executing "ninja all"...
[1/8] Performing build step for 'bootloader'
ninja: no work to do.
[2/6] Building C object esp-idf/main/CMakeFiles/__idf_main.dir/dhtdemo.c.obj
FAILED: esp-idf/main/CMakeFiles/__idf_main.dir/dhtdemo.c.obj
D:\Programs\Espressif\ESP-IDF-Tools\toolchain\bin\xtensa-esp32-elf-gcc.exe -DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\" -DUNI
TY_INCLUDE_CONFIG_H -DWITH_POSIX -Iconfig -I../main/. -I../../../../../components/newlib/platform_include -I../../../../../comp
onents/newlib/include -I../../../../../components/freertos/include -I../../../../../components/heap/include -I../../../../../co
mponents/log/include -I../../../../../components/soc/esp32/include -I../../../../../components/soc/include -I../../../../../com
ponents/esp_rom/include -I../../../../../components/esp_common/include -I../../../../../components/xtensa/include -I../../../..
/../components/xtensa/esp32/include -I../../../../../components/esp32/include -I../../../../../components/app_update/include -I
../../../../../components/spi_flash/include -I../../../../../components/bootloader_support/include -I../../../../../components/
mbedtls/port/include -I../../../../../components/mbedtls/mbedtls/include -I../../../../../components/lwip/include/apps -I../../
../../../components/lwip/include/apps/sntp -I../../../../../components/lwip/lwip/src/include -I../../../../../components/lwip/p
ort/esp32/include -I../../../../../components/lwip/port/esp32/include/arch -I../../../../../components/vfs/include -I../../../.
./../components/esp_wifi/include -I../../../../../components/driver/include -I../../../../../components/esp_ringbuf/include -I.
./../../../../components/esp_event/include -I../../../../../components/tcpip_adapter/include -I../../../../../components/ethern
et/include -I../../../../../components/efuse/include -I../../../../../components/efuse/esp32/include -I../../../../../component
s/pthread/include -I../../../../../components/app_trace/include -I../../../../../components/wpa_supplicant/include -I../../../.
./../components/wpa_supplicant/port/include -I../../../../../components/nvs_flash/include -I../../../../../components/smartconf
ig_ack/include -I../../../../../components/espcoredump/include -I../../../../../components/asio/asio/asio/include -I../../../..
/../components/asio/port/include -I../../../../../components/coap/port/include -I../../../../../components/coap/port/include/co
ap -I../../../../../components/coap/libcoap/include -I../../../../../components/coap/libcoap/include/coap2 -I../../../../../com
ponents/console/. -I../../../../../components/nghttp/port/include -I../../../../../components/nghttp/nghttp2/lib/includes -I../
../../../../components/esp-tls/. -I../../../../../components/esp_adc_cal/include -I../../../../../components/tcp_transport/incl
ude -I../../../../../components/esp_http_client/include -I../../../../../components/esp_http_server/include -I../../../../../co
mponents/esp_https_ota/include -I../../../../../components/openssl/include -I../../../../../components/esp_https_server/include
 -I../../../../../components/expat/expat/expat/lib -I../../../../../components/expat/port/include -I../../../../../components/w
ear_levelling/include -I../../../../../components/sdmmc/include -I../../../../../components/fatfs/src -I../../../../../componen
ts/freemodbus/common/include -I../../../../../components/idf_test/include -I../../../../../components/jsmn/include -I../../../.
./../components/json/cJSON -I../../../../../components/libsodium/libsodium/src/libsodium/include -I../../../../../components/li
bsodium/port_include -I../../../../../components/mdns/include -I../../../../../components/mqtt/esp-mqtt/include -I../../../../.
./components/protobuf-c/protobuf-c -I../../../../../components/protocomm/include/common -I../../../../../components/protocomm/i
nclude/security -I../../../../../components/protocomm/include/transports -I../../../../../components/spiffs/include -I../../../
../../components/ulp/include -I../../../../../components/unity/include -I../../../../../components/unity/unity/src -I../../../.
./../components/wifi_provisioning/include -mlongcalls -Wno-frame-address   -ffunction-sections -fdata-sections -fstrict-volatil
e-bitfields -nostdlib -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-but-set-variable -Wno-error=unused-variabl
e -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -ggdb -Og -std=gnu99 -Wno-old-style-declar
ation -DHAVE_CONFIG_H -DIDF_VER=\"v4.0-dev-562-g2b301f53e\" -DGCC_NOT_5_2_0=0 -DESP_PLATFORM -MD -MT esp-idf/main/CMakeFiles/__
idf_main.dir/dhtdemo.c.obj -MF esp-idf\main\CMakeFiles\__idf_main.dir\dhtdemo.c.obj.d -o esp-idf/main/CMakeFiles/__idf_main.dir
/dhtdemo.c.obj   -c ../main/dhtdemo.c
../main/dhtdemo.c:7:17: fatal error: dht.h: No such file or directory
compilation terminated.
ninja: build stopped: subcommand failed.
ninja failed with exit code 1

D) Therefore the dht.h file and directory cannot be found but i did added according book instructions at:
C:\Users\DELL\esp\esp-idf\components\dht\dht.h (also dht.c , etc are int that directory)

E) The original example use the statement #include <dht.h> but even changing that with an absolute path will not succeed (another error appear then)

#include <stdio.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "driver/gpio.h"
#include "sdkconfig.h"

#include <dht.h>
//include "C:\Users\DELL\esp\esp-idf\components\dht\dht.h"
static const dht_sensor_type_t sensor_type = DHT_TYPE_DHT22;
static const gpio_num_t dht_gpio = 26;

void dht_task(void *pvParameter)
{
    int16_t temperature = 0;
    int16_t humidity = 0;
    
    while(1) {
        if (dht_read_data(sensor_type, dht_gpio, &humidity, &temperature) == ESP_OK)
            printf("Humidity: %d%% Temp: %d^C\n", humidity / 10, temperature / 10);
        else
            printf("Could not read data from sensor\n");

        vTaskDelay(5000 / portTICK_PERIOD_MS);
        
    }
}

void app_main()
{
    xTaskCreate(&dht_task, "dht_task", configMINIMAL_STACK_SIZE, NULL, 5, NULL);
}

..i would appreciate a hint or solution on why the IDF toolchain does not find the dht.h header. Thank you!

**Comment by packt-pradeeps** [comment]
Hi @agusk please look into this issue

**Comment by packt-pradeeps** [comment]
Please reopen the issue if it still persists.

**Comment by solroshan** [comment]
Dear @jcabad100 , @packt-pradeeps,
Sorry for delay but i was just searcing on freertos dht codes and waves brought me to this issue.

dht.h not found for your demo cause of already this repo is not include dht.h file. You need to write your own file specially for this demo or maybe someone can share for others.
I'll be watching this repo for share my own esp32 freertos based dht codes when it works clean.
Bye.
